### ISSUE TITLE
feat: need handle the scenario when changing svc type from NodePort to clusterIP

### ISSUE THREAD

**Issue by yuchizh** [f5se/cis-c-docs#52]
Setup Details
CIS-C Version : 2.11.1
BIGIP Version: Big IP 15.1.6.1
Orchestration: K8S

Issue Description:
When user change svc type from NodePort to clusterIP, it doesn't trigger updates.

Steps To Reproduce
Created service in k8s with the service type "NodePort".
switch service type "NodePort" to "clusterIP"

Expected Result
The pool member will be updated.

Actual Result
Pool member keeps the same, no updates.

**Comment by zongzw** [comment]
Will fix in version 2.12.1. Thanks for reporting. @yuchizh

**Comment by olvandeng** [comment]
https://jira.pdsea.f5net.com/browse/OPENSTACK-2802 Need to support svc type from NodePort to clusterIP opened in JIRA to track this issue.

**Comment by myf5** [comment]
@yuchizh hi  pls test.

**Comment by myf5** [comment]
#54
