### ISSUE TITLE
Support flannel host-gw mode.

### ISSUE THREAD

**Issue by zongzw** [f5se/cis-c-docs#53]
Add flannel host-gw mode support aside with VXLAN mode.
Add more description if need. @kylinsoong

**Comment by olvandeng** [comment]
[OPENSTACK-2805](https://jira.pdsea.f5net.com/browse/OPENSTACK-2805) Add flannel host-gw mode support aside with VXLAN mode was opened and added into current sprint.

**Comment by zongzw** [comment]
#58 

@kylinsoong  please help to verify.

**Comment by kylinsoong** [comment]
Customer has verified that flannel Host-gw are supported.
