### ISSUE TITLE
Suggestion: Support cilium CNI

### ISSUE THREAD

**Issue by myf5** [f5se/cis-c-docs#56]
refer to https://github.com/f5devcentral/bigip-kubernetes-gateway/issues/52
Can also move the feature into CIS-C when available.

**Comment by olvandeng** [comment]
[OPENSTACK-2818](https://jira.pdsea.f5net.com/browse/OPENSTACK-2818) Support cilium CNI in CIS-C was opened to track the issue.

**Comment by zongzw** [comment]
Done: https://gitlab.f5net.com/cis-c/f5-kic/-/commit/2e7c27e05d4caa52a02ce92e7c76ebe5c53b08b4
