### ISSUE TITLE
Enhancement on CIS-C pre-stop hook

### ISSUE THREAD

**Issue by yuchizh** [f5se/cis-c-docs#57]
**Requirement Description:**
Customers have indicated a need for an enhancement to the CIS-C pre-stop hook. The current version of CIS-C has seen significant performance improvements and is now easier to configure. However, for scenarios that require higher SLA, considering the limitations of underlying compute resources, there is a requirement to proactively modify the status of F5 Pool Members in order to ensure better business continuity.

**Expected Behavior:**
Before a user's business pod goes offline or restarts, we would like to trigger the pre-stop function and use it to synchronize information with CIS-C. This function will be responsible for updating the frontend F5 device's pool members.

The parameters that need to be provided to CIS-C by the user include:

Namespace where the business resides.
Pod IP.
Service name of the business.
Graceful timeout period.
By incorporating this functionality, we can ensure that prior to a pod going offline or restarting, CIS-C receives the necessary information and can update the F5 device accordingly, facilitating seamless business continuity.

Please discuss and evaluate the feasibility and implementation approach for the above enhancement. Thanks!

**Comment by olvandeng** [comment]
[OPENSTACK-2819](https://jira.pdsea.f5net.com/browse/OPENSTACK-2819) Enhancement on CIS-C pre-stop hook was opened to track this issue.

**Comment by zongzw** [comment]
```shell
curl -X GET <cis-c-svc>:8080/hook/prestop \
    -H "pod-address: 10.42.0.155" \
    -H "action: disable|force-offline|remove" \
    -H "grace-period: 180" \
    -H "service-namespace: rest-tenant" \
    -H "service-name: rest-http"
```

字段含义： 

* `pod-address`:  prestop 事件触发所在pod的IP地址
* `action`: pretop时对pool member执行的操作，
   * `disable`：disable后，该member不再分配新的连接。注意，1）pool member将继续处理已存在的长连接。2）被持久化策略分配到该pool member的连接依旧会可以创建。
   * `force-offline`: pool member等待现有连接超时，但不允许任何新连接。
   * `remove`: 直接删除该pool member（暂不支持）。
* `grace-period`: k8s 侧 delete pod 时的优雅退出时长（`terminationGracePeriodSeconds`）
* `service-namespace`: pod所关联Service 的namespace，注意，如不方便可暂不提供；可多次使用，例如： `-H "service-namespace: A" -H "service-namespace: B" ...` 
* `service-name`: pod所关联Service的name，注意，如不方便可暂不提供；可多次使用。

**Comment by myf5** [comment]
1. More than 1 same messages may be sent to cis-c if there are more than 1 containers in the pod has pre-stop setting.
2. If k8s management service restart during the graceful termination, after restarting, pre-stop hook handler may be triggered again, so cis-c will get re-sending messages.
3. Depends on rolling update policy, cis-c may get concurrent pre-stop messages.
4. CIS-C need respond ASAP whenever the prestop message being received. should not block the container's terminating.

**Comment by myf5** [comment]
Also need consider the security, need some mechanism to make sure the cis-c's interface not being abused.

**Comment by zongzw** [comment]
Done: https://gitlab.f5net.com/cis-c/f5-kic/-/commit/22f24e72ceea7683c5963d8216b84989054c6cf9

For Testing, open 4 terminals, and each of them is used to:

1. monitoring k8s resource changes：
$ watch -n 1 kubectl --kubeconfig ~/.kube/k8s-1-19-calico.yaml get pod

2. monitoring bigip pool member status:
$ watch -n 1 'curl -k -u admin:P@ssw0rd123 https://10.250.15.109/mgmt/tm/ltm/pool/~service_tenant~service_app~service_pool/members 2>/dev/null | python -m json.tool | grep -E "(\"name\"|session)"'

3 use ab tool for http request test：
$ ab -n 200 -c 10 http://10.250.16.200/pam_namespace_helper

4. rollout the deployment for testing：
$ kubectl rollout restart deployment/rest-service-http-deployment

Finally, check the 'ab' terminal to see if there is "Failed Requests", normally, it is 0.

**Comment by zongzw** [comment]
用户测试反馈已经修复。
